name: avatar
description: Modulo avatar version 2.0

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/inicial/
    - assets/barbas/
    - assets/barbas/barbas_A/
    - assets/barbas/barbas_B/
    - assets/barbas/barbas_C/
    - assets/barbas/barbas_D/
    - assets/barbas/barbas_E/
    - assets/bocas/
    - assets/caras/cara_A/
    - assets/caras/cara_B/
    - assets/caras/cara_C/
    - assets/cejas/cejas_A/
    - assets/cejas/cejas_B/
    - assets/cejas/cejas_C/
    - assets/cejas/cejas_D/
    - assets/cuerpo/
    - assets/jugadores/
    - assets/muestras/
    - assets/narices/
    - assets/ojos/ojos_A/
    - assets/ojos/ojos_B/
    - assets/ojos/ojos_C/
    - assets/orejas/orejas_A/
    - assets/orejas/orejas_B/
    - assets/orejas/orejas_C/
    - assets/orejas/orejas_D/
    - assets/orejas/orejas_E/
    - assets/peinados/peinado_A/
    - assets/peinados/peinado_B/
    - assets/peinados/peinado_C/
    - assets/peinados/peinado_D/
    - assets/playeras/
    - assets/mujer/
    - assets/mujer/bocas/
    - assets/mujer/caras/
    - assets/mujer/caras/cara_A/
    - assets/mujer/caras/cara_B/
    - assets/mujer/caras/cara_C/
    - assets/mujer/cejas/
    - assets/mujer/cejas/cejas_A/
    - assets/mujer/cejas/cejas_B/
    - assets/mujer/cejas/cejas_C/
    - assets/mujer/cejas/cejas_D/
    - assets/mujer/cuerpo/
    - assets/mujer/narices/
    - assets/mujer/ojos/
    - assets/mujer/ojos/ojos_A/
    - assets/mujer/ojos/ojos_B/
    - assets/mujer/orejas/
    - assets/mujer/orejas/orejas_A/
    - assets/mujer/orejas/orejas_B/
    - assets/mujer/orejas/orejas_C/
    - assets/mujer/orejas/orejas_D/
    - assets/mujer/orejas/orejas_E/
    - assets/mujer/peinados/
    - assets/mujer/peinados/peinado_A/
    - assets/mujer/peinados/peinado_B/
    - assets/mujer/peinados/peinado_C/
    - assets/mujer/peinados/peinado_D/
    - assets/mujer/peinados/peinado_E/
    - assets/mujer/playeras/
    - assets/peinados_especiales/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
